/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("techinterviewbot.kotlin-library-conventions")
}
dependencies {
    implementation(project(":utilities"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    implementation("com.github.seratch:notion-sdk-jvm-core:1.8.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    // Excel
    implementation("org.apache.poi:poi:5.2.3")
    implementation("org.apache.poi:poi-ooxml:5.2.3")
}
