/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("techinterviewbot.kotlin-library-conventions")
}
dependencies {
    implementation(project(":utilities"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
}
